#!/usr/bin/env python
from __future__ import print_function, absolute_import, division

from ultimate_source_of_accounts.cli import main

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass

